# Generated by Django 5.2.6 on 2025-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
